### ISSUE TITLE
csanuragjain - Excess eth not refunded

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-nftport-judging#2]
csanuragjain

medium

# Excess eth not refunded

## Summary
While calling mint function, if user has provided extra eth then that will not be refunded back to user

## Vulnerability Detail
1. Observe the [mint function](https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/templates/NFTCollection.sol#L164)

```python
function mint(uint256 amount)
        external
        payable
        paymentProvided(amount * _runtimeConfig.publicMintPrice)
    {
        require(mintingActive(), "Minting has not started yet");

        _mintTokens(msg.sender, amount);
    }
```

2. Observe that this function only require (amount * _runtimeConfig.publicMintPrice) funds but in case if user provide more than that then the excess funds are not returned

## Impact
User will lose funds

## Code Snippet
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/templates/NFTCollection.sol#L164
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/templates/NFTCollection.sol#L176

## Tool used
Manual Review

## Recommendation
Kindly refund msg.value-(amount * _runtimeConfig.publicMintPrice) in case excess eth is provided

**Comment by hyperspacebunny** [comment]
Fixed in https://github.com/nftport/evm-minting-sherlock-fixes/pull/12
