### ISSUE TITLE
exd0tpy - Remain ether should refund to user.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-nftport-judging#20]
exd0tpy

medium

# Remain ether should refund to user.

## Summary
There is some function using `paidOnly` modifier. After execution main logic, overpaid ether should refund to caller.

## Vulnerability Detail
There is some function using `paidOnly` modifier. After execution main logic, overpaid ether should refund to caller.

## Impact
If user overpaid when using `deploy` and `call` in Factory.sol
## Code Snippet
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/Factory.sol#L147-L154
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/Factory.sol#L133-L139
## Tool used

Manual Review

## Recommendation
paidOnly should be like `require(msg.value == fee, "Insufficient payment");` or refund to user.

**Comment by hyperspacebunny** [comment]
Fixed in https://github.com/nftport/evm-minting-sherlock-fixes/pull/12
