### ISSUE TITLE
joestakey - `paymentProvided` validation can lead to user losing funds during minting

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-nftport-judging#29]
joestakey

medium

# `paymentProvided` validation can lead to user losing funds during minting

## Summary
paymentProvided validation can lead to user losing funds during minting

## Vulnerability Detail
`NFTCollection` uses a modifier `paymentProvided` in the minting functions, to ensure the caller sent enough `ETH` to mint the `amount` of NFTs they specified.

The issue is that it checks that `msg.value` is greater than the required payment:
```solidity
515:    require(msg.value >= payment, "Payment too small");
```
If the caller sends too much `msg.value`, that difference will not be refunded to them.

## Impact
The difference is not refunded to the caller in the minting functions.
Unless the `ADMIN` accounts for this difference upon calling `withdrawFees()`, the caller would permanently lose that amount.

## Code Snippet
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/templates/NFTCollection.sol#L515

## Tool used
Manual Review

## Recommendation
Ensure `paymentProvided` validates that the call sends exactly the price needed:

```diff
-515:    require(msg.value >= payment, "Payment too small");
+515:    require(msg.value == payment, "Payment too small");
```

**Comment by hyperspacebunny** [comment]
Fixed in https://github.com/nftport/evm-minting-sherlock-fixes/pull/12
