### ISSUE TITLE
rvierdiiev - ERC1155NFTProduct and ERC721NFTProduct contracts do not check if deploymentConfig.owner is provided

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-nftport-judging#49]
rvierdiiev

medium

# ERC1155NFTProduct and ERC721NFTProduct contracts do not check if deploymentConfig.owner is provided

## Summary
`ERC1155NFTProduct` and `ERC721NFTProduct` contracts do not check if deploymentConfig.owner is provided that leads to deploying contract without owner.
## Vulnerability Detail
`ERC1155NFTProduct` and `ERC721NFTProduct` contracts both use `initialize` [function](https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/templates/ERC1155NFTProduct.sol#L88-L107) after creating the contract. In both functions then `GranularRoles._initRoles` [function](https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/lib/GranularRoles.sol#L103-L149) is called to initialize owners, admins and other roles. `deploymentConfig.owner` param is passed to it to be an owner.

It's possible that contract creator will not provide `deploymentConfig.owner` to the `initialize` function. Then the owner will be [initialized](https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/lib/GranularRoles.sol#L106) to 0 address and admin role will be [granted](https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/lib/GranularRoles.sol#L106) to 0. Then user will lose control on his contract.
## Impact
Creator loses control on his contract.
## Code Snippet
Provided above.
## Tool used

Manual Review

## Recommendation
Add checking as it is in `NFTCollection` [here](https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/templates/NFTCollection.sol#L335).

**Comment by hyperspacebunny** [comment]
Fixed in https://github.com/nftport/evm-minting-sherlock-fixes/pull/8
