### ISSUE TITLE
Chom - Dust funds from buying NFT are not refunded

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-nftport-judging#66]
Chom

medium

# Dust funds from buying NFT are not refunded

## Summary
Dust funds from buying NFT are not refunded

## Vulnerability Detail

https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/templates/NFTCollection.sol#L164-L190

These two functions never return the dust fund to the user if exceeds ETH is paid.

## Impact

Dust funds from buying NFT are not refunded

## Code Snippet

https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/templates/NFTCollection.sol#L164-L190

https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/templates/NFTCollection.sol#L514-L517

## Tool used

Manual Review

## Recommendation
Either require exact msg.value == price or refund exceeds ETH paid.

```solidity
 modifier paymentProvided(uint256 payment) { 
     require(msg.value == payment, "Payment not equal"); 
     _; 
 } 
```

**Comment by hyperspacebunny** [comment]
Fixed in https://github.com/nftport/evm-minting-sherlock-fixes/pull/12
