### ISSUE TITLE
JohnnyTime - Deprecated function still exist in `Factory.sol`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-nftport-judging#9]
JohnnyTime

medium

# Deprecated function still exist in `Factory.sol`

## Summary
The @dev comments imply that some functionalities (mainly regarding fees) in the `factory.sol` contract are "deprecated and will be removed", but actually, these functions still exist and once the contract is deployed, they will be accessible on-chain.

## Vulnerability Detail
Deprecated features which still exist in the `factory` contract:
- The `deploy` function requires `deploymentFee` to be paid
- The `call` function requires `callFee` to be paid
- The `deploy` function with Signature should be deprecated
- The `setDeploymentFee` function should be deprecated
- The `setCallFee` function should be deprecated
- The `withdrawFees` function should be deprecated

## Impact
Stating the functions are deprecated while they actually exist and work in the contract can lead to distrust of users in the project.

## Code Snippet

Storage variables should be removed:
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/Factory.sol#L65-L69

`deploy` function deprecated functionality still exist:
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/Factory.sol#L127-L139

`call` function deprecated functionality still exist:
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/Factory.sol#L141-L154

`deploy` with `signature` param function still exist:
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/Factory.sol#L156-L176

`setDeploymentFee` and `setCallFee` Functions should be removed:
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/Factory.sol#L305-L321

`withdrawFees ` function should be removed (or maybe not, so it will be possible to rescue stuck ETH):
https://github.com/sherlock-audit/2022-10-nftport/blob/main/evm-minting-master/contracts/Factory.sol#L372-L378

## Tool used
Manual Review

## Recommendation
In case the need for the solidity function/feature is deprecated and not needed by the project, this feature/function should be removed and not deployed since the contract is immutable and it won't be able to remove it later.

**Comment by hyperspacebunny** [comment]
Fixed by https://github.com/nftport/evm-minting-sherlock-fixes/pull/16 and https://github.com/nftport/evm-minting-sherlock-fixes/pull/17

**Comment by rayn731** [comment]
Confirmed. The deprecated functions are removed.
